/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#1A56DB",
          hover: "#1E429F",
          light: "#EBF0FE",
          foreground: "#FFFFFF",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        surface: "#FFFFFF",
        "text-primary": "#1F2937",
        "text-secondary": "#6B7280",
        "text-tertiary": "#9CA3AF",
        success: "#10B981",
        "success-light": "#ECFDF5",
        warning: "#F59E0B",
        "warning-light": "#FEF3C7",
        danger: "#EF4444",
        "danger-light": "#FEF2F2",
        info: "#3B82F6",
        "info-light": "#EFF6FF",
        "chart-blue": "#3B82F6",
        "chart-cyan": "#06B6D4",
        "chart-indigo": "#6366F1",
        "chart-emerald": "#10B981",
        "chart-rose": "#F43F5E",
        "chart-amber": "#F59E0B",
        "chart-gray": "#9CA3AF",
        "border-light": "#F3F4F6",
        "page-bg": "#F0F4F8",
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        "card": "8px",
        "button": "6px",
        "input": "6px",
        "badge": "4px",
      },
      spacing: {
        "sidebar": "240px",
        "sidebar-collapsed": "64px",
        "topbar": "56px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "sm": "0 1px 2px rgba(0,0,0,0.04)",
        "md": "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        "lg": "0 4px 6px rgba(0,0,0,0.04), 0 2px 4px rgba(0,0,0,0.03)",
        "xl": "0 10px 15px rgba(0,0,0,0.05), 0 4px 6px rgba(0,0,0,0.03)",
      },
      fontSize: {
        "display": ["32px", { lineHeight: "40px", letterSpacing: "-0.64px", fontWeight: "700" }],
        "h1": ["24px", { lineHeight: "32px", letterSpacing: "-0.48px", fontWeight: "700" }],
        "h2": ["20px", { lineHeight: "28px", letterSpacing: "-0.4px", fontWeight: "700" }],
        "h3": ["16px", { lineHeight: "24px", letterSpacing: "-0.16px", fontWeight: "600" }],
        "body": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-small": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label": ["11px", { lineHeight: "16px", letterSpacing: "0.55px", fontWeight: "600" }],
        "data-large": ["28px", { lineHeight: "36px", letterSpacing: "-0.56px", fontWeight: "700" }],
        "data-medium": ["20px", { lineHeight: "28px", letterSpacing: "-0.4px", fontWeight: "600" }],
        "nav-item": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "nav-active": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "table-header": ["12px", { lineHeight: "18px", letterSpacing: "0.6px", fontWeight: "600" }],
        "table-cell": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "chart-label": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "badge-text": ["12px", { lineHeight: "16px", letterSpacing: "0.24px", fontWeight: "600" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.5", transform: "scale(1.2)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "shimmer": "shimmer 1.5s ease-in-out infinite",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        "slide-up": "slide-up 0.5s ease-out forwards",
        "slide-in-right": "slide-in-right 0.4s ease-out forwards",
        "fade-in": "fade-in 0.3s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
